{% set name = "genpy" %}
{% set version = "2021.1" %}
{% set sha256 = "9bc062fa98c5c466ff464d8974be81a6bf67af9247b5e5176215ad1e81a6cdac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pytools
    - six

test:
  imports:
    - {{ name }}

about:
  home: http://pypi.python.org/pypi/genpy
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: AST-based Python source generation
  dev_url: http://github.com/inducer/genpy

extra:
  recipe-maintainers:
    - inducer
    - isuruf
