travis:
  secure:
    BINSTAR_TOKEN: vOwY8psGHAEWUvW2Pmtuv+w1izDRmQUVA01o+iD/tCv+xIf/I7KtVDn+htZ3W4kHNgKr0b+yhCQh5J5G6Q1bG36peg/q/bzs+ukT5l1mIrYFNxiPqFWlOeoWN+LIa9T7dSBvzrFimEiLS5WOGSmhAeXrYhskT+NdGOO2puXwfwGRpVsVkU2lE6EGEFnI1Xz7iZziVHWzwn4mJbTJH3beNPjyUFogpFAtYaOk3Pf2vfti5hCzy65sFVyGTOkxbgj2YPGrTm64IlgHyLAl+Ebkq1l0sxWhluQQFiqBsv1no7tqCd5sNYj640W7cgvYfBPbGPKRcZKZWltkqK+YFFGKheOu1oVYrzp8wx0HqV55sVAKNKMmuIhMluw9w+Lb5Ejq1lWgY/TEPCnfpYUXWW9jTtWrX90vmZT6S0zqLQ7yeaquCWiacozuI2XFkM9rGdx74uVU8s/CQ+LI41ewGYvJ70HmS3hRKO4EsFfZo1cAHwFtsg7AxMB+CImJgQVsVyOv4FVRWZWYN7Y4DVh+xekrFieYncUzob7Nd2EJxIOeRl+OSF9xUZLLqp0bpuEnb7eP5w7g5H6jaQ6X0egcUqgNXQJzZHbOSJ8ykoBIbDzl3WR3kjyp/iIS6d7cCVaPBelyEJ5A0Iv1qgaBhE6Y3H5EniahozsCDMD6KC5v3cvMwhA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
